Add oci.artifact.manifest reference type persistence docs
notaryproject/distribution pull request #9
Opened 2021-04-22 00:01 UTC by SteveLasker

Adds docs for the persistence of reference types

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

2021-04-22 00:02 UTC, SteveLasker commented
@aviral26, @shizhMSFT 👀

2021-04-23 04:24 UTC, aviral26 requested changes

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +- Implements a proposed [oci.artifact.manifest][oci-artifact-manifest], utilizing a `[manifest-refs]` collection
Prototype-2 implements a collection called `manifests`

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +- Implements the [oci.artifact.manifest][oci-artifact-manifest] `/v2/_ext/oci-artifacts/v1/{repository}/manifests/{digest}/referrers` API to identify referenced artifacts. Such as what signatures, or
The implemented API is `references`

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +The [oci.artifact.manifest spec][oci-artifact-manifest-spec] outlines how reference types may be added to a registry creating a single references, such as signed content to a graph of reference inclu
Grammatical error? This sentence is a bit complex, especially because it does not define a reference type.

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +To query the artifacts which reference `net-monitor:v1`, the [oci.artifact.manifest spec][oci-artifact-manifest-spec] provides a [referrers api][oci-artifact-referrers-api] as an extension to the [di
`references` for consistency.

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +`GET {registry}/v2/_ext/oci-artifacts/v1/net-monitor/manifests/sha256:73c803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a3c333/references?artifactType=application/vnd.cncf.notary.v2`
The implemented API uses a query parameter called `artifact-type`

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +*This experimental branch* of CNCF Distribution implements reference types, enabling the ability to query reference types. To query referenced artifacts, a reverse-lookup is required. For example whe
Are "referenced types" and "referenced artifacts" used interchangeably? If so, let's use only one for consistency.

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +*This experimental branch* of CNCF Distribution implements reference types, enabling the ability to query reference types. To query referenced artifacts, a reverse-lookup is required. For example whe
This statement is unclear. It does not clarify:
1. What the metadata store is
2. Which metadata store is used to record the reference (Ans: the referred manifest's)

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +Using the existing [OCI distribution-spec push][oci-dist-spec-manifest-put] api to push an [oci.artifact.manifest][oci-image-manifest-spec] with the added `"artifactType": "application/vnd.cncf.notar
Should be .... "a `[manifests]` property containing the descriptor of the `net-monitor:v1` image"

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +                        │               └── 8ac803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a3c222 (signature)
To a first time reader, this might be confusing since the signature is only a blob.

To clarify, this should be called `signature artifact manifest`

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +> NOTE: the node immediately below `ref` is the `oci.image.manifest.artifactType` of the manifest. This node provides the indexing by type. Since `mediaTypes` contain invalid characters for storage (
`artifactType`

2021-04-23 04:24 UTC, aviral26 commented on docs/reference-types.md
> +To represent an image which is signed, with an SBoM which is also signed, the following persistance would be made:
nit: `persistence`

2021-04-23 19:34 UTC, SteveLasker commented on docs/reference-types.md
> +- Implements a proposed [oci.artifact.manifest][oci-artifact-manifest], utilizing a `[manifest-refs]` collection
I was wondering what the alternative names would look like and forgot to change them back.

2021-04-23 19:47 UTC, SteveLasker commented on docs/reference-types.md
> +*This experimental branch* of CNCF Distribution implements reference types, enabling the ability to query reference types. To query referenced artifacts, a reverse-lookup is required. For example whe
Do you have a suggestion on how to explain this better?

2021-04-23 19:50 UTC, SteveLasker commented on docs/reference-types.md
> +                        │               └── 8ac803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a3c222 (signature)
I've added " manifest" to each reference

2021-04-23 21:11 UTC, merged

2021-04-23 21:14 UTC, SteveLasker commented
I accidentally pushed to `notaryproject/distribution:prototype-2`, rather than my fork. We can open issues for any changes.